import turtle
tortuguita=turtle.Turtle()
tortuguita.pensize(15)
tortuguita.pencolor("Yellow")
tortuguita.shape("arrow")
tortuguita.left(90)
tortuguita.forward(70)
tortuguita.right(150)
tortuguita.forward(80)
tortuguita.left(150)
tortuguita.forward(70)


tortuguita=turtle.Turtle()
tortuguita.shape("arrow")
tortuguita.pensize(15)
tortuguita.pencolor("light green")
tortuguita.penup()
tortuguita.goto((40, 0))
tortuguita.forward(20)
tortuguita.pendown()
tortuguita.left(90)
tortuguita.forward(70)


tortuguita=turtle.Turtle()
tortuguita.shape("arrow")
tortuguita.pensize(15)
tortuguita.pencolor("light blue")
tortuguita.penup()
tortuguita.goto((80, 0))
tortuguita.pendown()
tortuguita.left(90)
tortuguita.forward(70)
tortuguita.right(90)
tortuguita.forward(30)
tortuguita.left(180)
tortuguita.forward(30)
tortuguita.goto((80, 0))
tortuguita.left(180)
tortuguita.forward(30)


tortuguita=turtle.Turtle()
tortuguita.shape("arrow")
tortuguita.pensize(15)
tortuguita.pencolor("light pink")
tortuguita.penup()
tortuguita.goto((130, 0))
tortuguita.pendown()
tortuguita.left(90)
tortuguita.forward(70)
tortuguita.right(90)
tortuguita.forward(50)
tortuguita.right(90)
tortuguita.forward(70)
tortuguita.right(90)
tortuguita.forward(50)


tortuguita=turtle.Turtle()
tortuguita.shape("arrow")
tortuguita.pensize(15)
tortuguita.pencolor("Cyan")
tortuguita.penup()
tortuguita.goto((200, 0))
tortuguita.pendown()
tortuguita.left(90)
tortuguita.forward(70)
tortuguita.goto((200, 0))
tortuguita.right(90)
tortuguita.forward(30)


tortuguita=turtle.Turtle()
tortuguita.shape("arrow")
tortuguita.pensize(15)
tortuguita.pencolor("Cyan")
tortuguita.penup()
tortuguita.goto((250, 0))
tortuguita.pendown()
tortuguita.left(90)
tortuguita.forward(70)
tortuguita.goto((250, 0))
tortuguita.right(90)
tortuguita.forward(30)


tortuguita=turtle.Turtle()
tortuguita.shape("arrow")
tortuguita.pensize(15)
tortuguita.pencolor("Purple")
tortuguita.penup()
tortuguita.goto((300, 0))
tortuguita.pendown()
tortuguita.left(90)
tortuguita.forward(70)
tortuguita.right(90)
tortuguita.forward(30)
tortuguita.right(90)
tortuguita.forward(30)
tortuguita.right(90)
tortuguita.forward(30)
tortuguita.right(-140)
tortuguita.forward(0)
tortuguita.goto((300, 0))
tortuguita.left(-320)
tortuguita.forward(30)

t=turtle.Turtle()
t.speed(0)
t.pencolor("green")
t.pensize(2)
for x in range (10):
    t.rt(60)
    for y in range (10):
        t.fd(15)
        t.rt(15)
    t.rt(90)
    for z in range (10):
        t.fd(15)
        t.rt(15)
    t.rt(90)